### ISSUE TITLE
Using Toasts instead of Alerts

### ISSUE THREAD

**Issue by Anikaaasingh** [Harsh-Singh-Rajput/Notepad#1]
I would like to replace local alerts with appealing toast messages. Can I contribute to the same?

**Comment by Harsh-Singh-Rajput** [comment]
Yes, you can this will be more appealing and natural. Looking forward for it😀

**Comment by Harsh-Singh-Rajput** [comment]
> I would like to replace local alerts with appealing toast messages. Can I contribute to the same?
Yes, you can this will be more appealing and natural. Looking forward for it😀

**Comment by Harsh-Singh-Rajput** [comment]
Issue Resolved
