### ISSUE TITLE
Fix the button alignment on the toolbar and add the active states to the button 

### ISSUE THREAD

**Issue by Harsh-Singh-Rajput** [Harsh-Singh-Rajput/Notepad#13]
Add the active states to the button so that user can know which button functionality is applying on text

**Comment by mritul** [comment]
Can I work on this issue ?

**Comment by mritul** [comment]
@Harsh-Singh-Rajput sure I'll work on it

**Comment by mritul** [comment]
@Harsh-Singh-Rajput I've finished providing active states to the other buttons as well, I've also attached a screenshot of the changes.Kindly review the PR.

![image](https://user-images.githubusercontent.com/84136875/193794901-974cc048-f8b5-48b2-9176-80364a5d58cf.png)

**Comment by mritul** [comment]
@Harsh-Singh-Rajput  I've also made the save and delete buttons more uniform like the other buttons and provided some padding to the buttons and also aligned all of them in one line with flexbox.

![image](https://user-images.githubusercontent.com/84136875/193799134-e677629a-1803-4917-9948-eab8c8bcb8a8.png)

**Comment by Harsh-Singh-Rajput** [comment]
@mritul can you pull the latest changes and then add these features again since there is conflict because you didnt pull the latest changes from the repo and make sure that dark mode feature not affected by the changes you made
