### ISSUE TITLE
Make the project responsive for small screen sizes

### ISSUE THREAD

**Issue by RhyshaKachari** [Harsh-Singh-Rajput/Notepad#16]
Objectives:
->Enhancing the responsiveness of the project

**Comment by RhyshaKachari** [comment]
@Harsh-Singh-Rajput  I can solve this issue by using simple CSS . Kindly assign me this issue :)

**Comment by Harsh-Singh-Rajput** [comment]
@RhyshaKachari I already assigned this issue to you,
You can start working on it
