### ISSUE TITLE
I want to add css to buttons in order to make them more attractive 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [Harsh-Singh-Rajput/Notepad#17]
I want to add css to buttons in order to make them more attractive can i ? They are looking very basic especially the bold/italic , dark and light mode buttons . can you assign it to me .

**Comment by AjayMaheshwari23** [comment]
@Harsh-Singh-Rajput I have opened this issue 23 hrs ago can you please assign it to me

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput I have opened this issue 23 hrs ago can you please assign it to me

ok go for it sorry for late reply
