### ISSUE TITLE
Make the buttons more attractive and better placement.

### ISSUE THREAD

**Issue by akshit5565** [Harsh-Singh-Rajput/Notepad#19]
I want to contribute to this project by changing and adding css to the buttons and also changing their placement for more professional look.
I want to do this unfer the hacktoberfest.

**Comment by akshit5565** [comment]
@Harsh-Singh-Rajput please assign me the following task
Thank you!!

**Comment by Harsh-Singh-Rajput** [comment]
> @Harsh-Singh-Rajput please assign me the following task Thank you!!
I already assigned this issue to someone, so if he didnt complete it I will assign it to  you
