### ISSUE TITLE
File lists overflow out of the viewport

### ISSUE THREAD

**Issue by iamashay** [Harsh-Singh-Rajput/Notepad#24]
After saving more than 17 files, they overflow out of their parent container.

- [ ] Fix overflowing file lists

I am willing to work on this.

**Comment by Harsh-Singh-Rajput** [comment]
> After saving more than 17 files, they overflow out of their parent container.
> 
> * [ ]  Fix overflowing file lists
> 
> I am willing to work on this.

@iamashay go for it sorry for late reply

**Comment by iamashay** [comment]
Yeah, I'm on it.
