### ISSUE TITLE
Bug while saving the file without giving the name for the file

### ISSUE THREAD

**Issue by Harsh-Singh-Rajput** [Harsh-Singh-Rajput/Notepad#4]
The expected response for this behaviour for this task should be something like that it will give user an alert/error that file name is not given try again.

[](https://user-images.githubusercontent.com/61553586/193422734-ec122d0e-a469-49c0-9c2d-f4bbc47f5f7e.mp4
)

**Comment by Neesh774** [comment]
Will work on this.

**Comment by Harsh-Singh-Rajput** [comment]
@Neesh774 Sorry I didn't stated the reason here since manipta fixed this issue before you so I merged his PR. You can look into other issues of the repo
