### ISSUE TITLE
Add Dark/Light Mode in textEditor 

### ISSUE THREAD

**Issue by KedarKK1** [Harsh-Singh-Rajput/Notepad#9]
<h1>Kindly Assign tis task to me</h1> @Harsh-Singh-Rajput @manipta @Anikaaasingh  I can add Dark/Light mode to the divisions

**Comment by Harsh-Singh-Rajput** [comment]
Yes I wanted to implement the Dark and light mode and was planning to add this as feature.
I assigned this task to you.
Looking forward to it
